title: Thinking Slightly
author: Ali Abid
tagline: >-
  Senior Software Engineer
email: info@thinkingslightly.com
description: >-
  Ali Abid — Software engineer and product builder.
baseurl: ""
url: ""

# Social
linkedin_username: aliencoded
github_username:   aliabiddev
github_username2:  aliencoded

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
excerpt_separator: <!-- excerpt-end -->

# Google Analytics
google_analytics: UA-194867527-1
